export const COLORS_MAP = {
    red: { bg: "bg-red-50", text: "text-red-600", border: "border-red-300" },
    orange: { bg: "bg-orange-50", text: "text-orange-600", border: "border-orange-300" },
    amber: { bg: "bg-amber-50", text: "text-amber-600", border: "border-amber-300" },
    yellow: { bg: "bg-yellow-50", text: "text-yellow-600", border: "border-yellow-300" },
    lime: { bg: "bg-lime-50", text: "text-lime-600", border: "border-lime-300" },
    green: { bg: "bg-green-50", text: "text-green-600", border: "border-green-300" },
    emerald: { bg: "bg-emerald-50", text: "text-emerald-600", border: "border-emerald-300" },
    teal: { bg: "bg-teal-50", text: "text-teal-600", border: "border-teal-300" },
    cyan: { bg: "bg-cyan-50", text: "text-cyan-600", border: "border-cyan-300" },
    sky: { bg: "bg-sky-50", text: "text-sky-600", border: "border-sky-300" },
    blue: { bg: "bg-blue-50", text: "text-blue-600", border: "border-blue-300" },
    indigo: { bg: "bg-indigo-50", text: "text-indigo-600", border: "border-indigo-300" },
    violet: { bg: "bg-violet-50", text: "text-violet-600", border: "border-violet-300" },
    purple: { bg: "bg-purple-50", text: "text-purple-600", border: "border-purple-300" },
    fuchsia: { bg: "bg-fuchsia-50", text: "text-fuchsia-600", border: "border-fuchsia-300" },
    pink: { bg: "bg-pink-50", text: "text-pink-600", border: "border-pink-300" },
    rose: { bg: "bg-rose-50", text: "text-rose-600", border: "border-rose-300" },
    slate: { bg: "bg-slate-50", text: "text-slate-600", border: "border-slate-300" },
    gray: { bg: "bg-gray-50", text: "text-gray-600", border: "border-gray-300" },
    zinc: { bg: "bg-zinc-50", text: "text-zinc-600", border: "border-zinc-300" },
    neutral: { bg: "bg-neutral-50", text: "text-neutral-600", border: "border-neutral-300" },
    stone: { bg: "bg-stone-50", text: "text-stone-600", border: "border-stone-300" },
} as const
